export const GET_AUCTION_ITEMS = 'GET_AUCTION_ITEMS';
export const SET_AUCTION_ITEMS = 'SET_AUCTION_ITEMS';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';

